export interface GameResponse {
    id: number,
    playerName: string,
    score: number,
    level: number,
    duration: number,
    shotsFired: number,
    largeUfosDestroyed: number,
    smallUfosDestroyed: number,
    asteroidsDestroyed: number,
    randomSeed: string,
    log: string,
    version: string,
    timeAdded: string,
}
